# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'University of Washington'
    description: 'Bingbing Wen - PhD Student at University of Washington. Research focuses on building trustworthy foundation models.'
    twitter: 'bingbingwen1'
  analytics:
    google_analytics: 'UA-155581705-1'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Bingbing Wen'

# Site footer
footer:
  copyright:
    notice: '© {year} Bingbing Wen. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

# Avatar settings
avatar:
  size: 300

# Custom CSS
custom_css:
  - "/css/custom.css"
  - "/stylesheet.css"
